# Generated by Django 3.0.2 on 2020-08-28 12:27

import audiofield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Artist', models.CharField(max_length=250)),
                ('SongTitle', models.CharField(max_length=250)),
                ('audio', audiofield.fields.AudioField(blank=True, help_text='Allowed type - .mp3, .wav, .ogg', upload_to='media/upload/')),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
