# Generated by Django 3.0.2 on 2020-05-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=250)),
                ('audio_src', models.CharField(max_length=250)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
